# Generated by Django 2.0.5 on 2018-08-29 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.BooleanField(default=False)),
                ('phone', models.BooleanField(default=False)),
                ('read', models.BooleanField(default=False)),
                ('bounced', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('response_seconds', models.IntegerField(blank=True, null=True)),
                ('rsvp', models.BooleanField(default=False)),
                ('rsvp_answer', models.NullBooleanField()),
                ('unauth_rsvp_token', models.CharField(default=uuid.uuid4, editable=False, max_length=255, null=True, unique=True)),
                ('unauth_rsvp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InboundSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('from_number', models.CharField(blank=True, max_length=255, null=True)),
                ('to_number', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('format', models.CharField(choices=[('page', 'Page'), ('password_reset', 'Password reset'), ('cert_notice', 'Cert notice'), ('do_shift_starting', 'DO Shift Starting'), ('do_shift_pending', 'DO Shift Pending')], max_length=255)),
                ('ancestry', models.CharField(blank=True, max_length=255, null=True)),
                ('period_format', models.CharField(blank=True, choices=[('invite', 'invite'), ('info', 'info'), ('broadcast', 'broadcast'), ('leave', 'leave'), ('return', 'return')], max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_rsvp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.Message')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Period')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('opened', models.BooleanField(default=False)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Distribution')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Email')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutboundSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('delivered', models.BooleanField(default=False)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Distribution')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RsvpTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('yes_prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('no_prompt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='message',
            name='rsvp_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='message.RsvpTemplate'),
        ),
        migrations.AddField(
            model_name='distribution',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Message'),
        ),
    ]
