# Generated by Django 2.0.13 on 2019-04-18 04:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models.file


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190115_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255)),
                ('extension', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=255)),
                ('size', models.IntegerField()),
                ('file', models.ImageField(max_length=255, upload_to=main.models.file.file_upload_path_handler)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
    ]
