# Generated by Django 2.0.13 on 2019-05-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20190422_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role',
            field=models.CharField(blank=True, choices=[('UL', 'Unit Leader'), ('Bd', 'Board Member'), ('XO', 'Executive Officer'), ('OO', 'Operations Officer'), ('SEC', 'Secretary'), ('TO', 'Training Officer'), ('RO', 'Recruiting Officer'), ('TRS', 'Treasurer'), ('OL', 'Operators Leader'), ('WEB', 'Web Master'), ('DOS', 'DO Scheduler'), ('TM', 'Active Technical Member'), ('FM', 'Active Field Member'), ('T', 'Active Trainee')], max_length=255),
        ),
    ]
