# Generated by Django 2.0.13 on 2019-11-18 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190501_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doavailable',
            name='available',
            field=models.NullBooleanField(default=None),
        ),
    ]
