# Generated by Django 2.2.13 on 2020-07-20 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20191117_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('fileId', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('AAR', 'After Action Report'), ('AHC', 'AHC Log'), ('DO', 'DO Log'), ('L', 'Logistics / Carpool Spreadsheet'), ('TP', 'Training Plan')], max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('destinationId', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='DoLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fileId', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(blank=True, choices=[('AAR', 'After Action Report'), ('AHC', 'AHC Log'), ('DO', 'DO Log'), ('L', 'Logistics / Carpool Spreadsheet'), ('TP', 'Training Plan')], max_length=255)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField()),
                ('week', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
