# Generated by Django 2.2.13 on 2020-09-14 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_docs_20200819'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='logistics',
            field=models.BooleanField(default=False),
        ),
    ]
