# Generated by Django 2.2.13 on 2020-10-10 03:57

from django.db import migrations, models
import main.lib.phone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_participant_logistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.CharField(max_length=255, validators=[main.lib.phone.validate_phone]),
        ),
    ]
