# Generated by Django 2.2.13 on 2020-11-07 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201009_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_private',
            field=models.TextField(blank=True, help_text='This text will be added to the description text above.', null=True, verbose_name='Additional private description'),
        ),
        migrations.AddField(
            model_name='event',
            name='gcal_id_private',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_private',
            field=models.CharField(blank=True, default='', help_text='Replaces location field on internal calendar.', max_length=255, verbose_name='Private version of location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gcal_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
