# Generated by Django 3.2.13 on 2022-06-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_event_cal_private'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distribution',
            name='rsvp_answer',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='doavailable',
            name='available',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
