# Generated by Django 3.2.13 on 2022-06-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20220624_2322'),
        ('main', '0014_history'),
    ]

    operations = [
    ]
