# Generated by Django 3.2.13 on 2022-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_merge_0014_auto_20220624_2322_0014_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundsms',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
