# Generated by Django 3.2.13 on 2022-08-22 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('main', '0017_auto_20220809_2235'), ('main', '0018_auto_20220810_2045'), ('main', '0019_auto_20220810_2231'), ('main', '0020_auto_20220821_2339')]

    dependencies = [
        ('main', '0016_alter_inboundsms_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255)),
                ('show_combined', models.BooleanField(default=False)),
                ('has_earned_date', models.BooleanField(default=True)),
                ('has_expiration_date', models.BooleanField(default=True)),
                ('has_description', models.BooleanField(default=True)),
                ('has_link', models.BooleanField(default=False)),
                ('has_file', models.BooleanField(default=True)),
                ('hide_in_summary', models.BooleanField(default=False)),
                ('help_text', models.TextField(blank=True)),
                ('max_display_length', models.IntegerField(default=255)),
                ('responsive_priority', models.IntegerField(default=1)),
                ('display_only', models.BooleanField(default=False)),
                ('template', models.TextField(blank=True)),
                ('display_name', models.CharField(blank=True, help_text='Optional shorter name for display.', max_length=255)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cert',
            name='earned_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cert',
            name='type',
            field=models.CharField(choices=[('medical', 'Medical'), ('cpr', 'CPR'), ('ham', 'Ham'), ('tracking', 'Tracking'), ('avalanche', 'Avalanche'), ('rigging', 'Rigging'), ('ics', 'ICS'), ('overhead', 'Overhead'), ('driver', 'SO Driver'), ('background', 'SO Background')], max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='CertSubType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1, null=True)),
                ('name', models.CharField(max_length=255)),
                ('is_other', models.BooleanField(default=False)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.certtype')),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cert',
            name='subtype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.certsubtype'),
        ),
        migrations.AlterField(
            model_name='cert',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
