# Generated by Django 3.2.16 on 2025-02-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='type',
            field=models.CharField(blank=True, choices=[('medical', 'Medical'), ('cpr', 'CPR'), ('ham', 'Ham'), ('tracking', 'Tracking'), ('avalanche', 'Avalanche'), ('rigging', 'Rigging'), ('ics', 'ICS'), ('overhead', 'Overhead'), ('driver', 'SO Driver'), ('background', 'SO Background')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='published',
            field=models.BooleanField(default=False, help_text='Published events are viewable on the public and private calendar.'),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='published',
            field=models.BooleanField(default=False, help_text='Published events are viewable on the public and private calendar.'),
        ),
    ]
