# Generated by Django 2.0.3 on 2018-05-23 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('error_code', models.IntegerField(blank=True, null=True)),
                ('error_message', models.CharField(blank=True, max_length=255, null=True)),
                ('distribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnet.Distribution')),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bnet.Phone')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
