# Generated by Django 2.0.5 on 2018-06-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bnet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RsvpTemplates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.IntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('yes_prompt', models.CharField(blank=True, max_length=255, null=True)),
                ('no_prompt', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'ordering': ['position'],
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='address',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='emergencycontact',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='otherinfo',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='phone',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='message',
            name='linked_rsvp_id',
        ),
        migrations.AddField(
            model_name='message',
            name='linked_rsvp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bnet.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='format',
            field=models.CharField(choices=[('page', 'Page'), ('password_reset', 'Password reset'), ('cert_notice', 'Cert notice'), ('do_shift_starting', 'DO Shift Starting'), ('do_shift_pending', 'DO Shift Pending')], max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='period_format',
            field=models.CharField(blank=True, choices=[('invite', 'invite'), ('info', 'info'), ('broadcast', 'broadcast'), ('leave', 'leave'), ('return', 'return')], max_length=255, null=True),
        ),
    ]
