# Generated by Django 2.0.3 on 2018-05-24 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnet', '0002_outboundsms'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundSms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sid', models.CharField(blank=True, max_length=255, null=True)),
                ('from_number', models.CharField(blank=True, max_length=255, null=True)),
                ('to_number', models.CharField(blank=True, max_length=255, null=True)),
                ('body', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
