# Generated by Django 2.0.3 on 2018-05-29 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bnet', '0004_outboundemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundemail',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='outboundemail',
            name='opened',
            field=models.BooleanField(default=False),
        ),
    ]
