# This is a basic workflow to help you get started with Actions

name: Azure Swap Slots - Staging <-> Production

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_WEBAPP_NAME: ${{ secrets.AZURE_WEBAPP_NAME }}
  AZURE_WEBAPP_SLOT: ${{ secrets.AZURE_WEBAPP_SLOT }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  swap:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        allow-no-subscriptions: true

    - name: Azure CLI Action
      uses: Azure/cli@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
          az webapp deployment slot swap --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --slot ${{ env.AZURE_WEBAPP_SLOT }} --target-slot production
          echo "https://$(az webapp show --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_WEBAPP_NAME }} --query hostNames[0] -o tsv)"
